apps/register/urls.py
from django.urls import path

from . import views
app_name = 'accounts'
urlpatterns = [
    path('', views.index,name='index'),
    path('register/', views.register,name='register'),
    path('success/', views.success),
    path('login/', views.user_login,name='login'),

    path('logout/', views.user_logout, name ='logout')
]

contact/messages/urls.py
from django.conf.urls import url

from . import views

app_name = "pinax_messages"

urlpatterns = [
    url(r"^inbox/$", views.InboxView.as_view(),
        name="inbox"),
    url(r"^create/$", views.MessageCreateView.as_view(),
        name="message_create"),
    url(r"^create/(?P<user_id>\d+)/$", views.MessageCreateView.as_view(),
        name="message_user_create"),
    url(r"^thread/(?P<pk>\d+)/$", views.ThreadView.as_view(),
        name="thread_detail"),
    url(r"^thread/(?P<pk>\d+)/delete/$", views.ThreadDeleteView.as_view(),
        name="thread_delete"),
]

main/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path
from main import settings

from django.conf.urls.static import static
urlpatterns = [
path('Post/', include('products.urls')) ,
path('Notes/', include('notes.urls')) ,
    path('', include('apps.register.urls')),
url(r"^messages/", include("pinax.messages.urls", namespace="pinax_messages")),
url(r'^ratings/', include('star_ratings.urls', namespace='ratings')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

notes/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, re_path

from main import settings
from .views import (
    post_list,

    post_create,
post_detail,
    post_update,
    post_delete,


)
app_name='notes'
urlpatterns = [
    path('', post_list, name='home'),
    path('create', post_create,name='create_post'),

    re_path(r'^(?P<slug>[\w-]+)/$', post_detail, name='detail'),
    re_path(r'^(?P<slug>[\w-]+)/edit/$', post_update, name='update'),
    re_path(r'^(?P<slug>[\w-]+)/delete/$', post_delete),
    ]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/index.html
<!DOCTYPE HTML>


{% load static i18n%}
{%  load staticfiles %}

<html>
	<head>
		<title>Index</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
 <link rel="stylesheet" href="{% static 'assets/css/main.css' %}">

	</head>
	<body class="landing is-preload">
		<div id="page-wrapper">

			<!-- Header -->
				<header id="header" class="alt">
					<h1><a href="{% url "accounts:index"  %}">TRADE-EX</a></h1>
					<nav id="nav">
						<ul>
							<li><a href="{% url 'accounts:index' %}">Home</a></li>
                            <li><a href="{% url 'index' %}">Products  </a></li>
                        <li><a href="{% url 'notes:home' %}">View Notes </a></li>


                         <a href="{% url 'pinax_messages:inbox' %}"><i class="fa fa-envelope"></i> {% trans "Message Inbox" %}</a>
                            {%  if user.is_authenticated %}
                            <li> <a href="{% url 'accounts:logout' %}" class="button">Logout</a></li>
                            {% else %}
							<li><a href="{% url 'accounts:login' %}" class="button">Login</a></li>

                            {% endif %}
						</ul>
					</nav>
				</header>

			<!-- Banner -->
				<section id="banner">
					<h2>TRADE-EX</h2>
					<p>ONLINE TRADING PORTAL</p>
					<ul class="actions special">
                        {%  if user.is_authenticated %}
                            <li><a href="{% url 'create_post' %}" class="button primary">Post AD</a></li>
                        {% else %}
						<li><a href="{% url 'accounts:register' %}" class="button primary">Sign Up</a></li>
                        {% endif %}
						<li><a href="#" class="button">Learn More</a></li>
					</ul>


				</section>
            
            
            
            
            
            
            
            
										

			<!-- Main -->
				<section id="main" class="container">

					<section class="box special">
						<header class="major">
							<h2>Introducing the ultimate trading app
							<br /></h2>
							<p>Trade-ex is an on-demand used college material exchange platform which works by connecting university students to buy and sell their hostel reusable material or appliances and study materials locally.
	We connect the buyers and sellers and beyond that provide them a network for making the trades possible.
</p>
						</header>
						<span class="image featured"><img src={% static "assets/images/pic01.jpg" %}  /></span>

					</section>

					<section class="box special features">
						<div class="features-row">
							<section>
								<span class="icon major fa-bolt accent2"></span>
								<h3>Share knowledge. Get paid.</h3>
								<p> Not only can you make money, but you’re helping students in need of additional study materials.
		Trade-ex provides a safe atmosphere where college students can connect for notes, used books and other materials that can be used for college.<br>
		 You can sell<br>
	•Lecture Notes<br>
	•Study Guides<br>
    •Flashcards<br>
    •Handouts<br>
	•Test Reviews</p>
                            </section>
							<section>
								<span class="icon major fa-area-chart accent3"></span>
								<h3></h3>
								<p></p>
							</section>
						</div>
						<div class="features-row">
							<section>
								<span class="icon major fa-cloud accent4"></span>
								<h3>CHAT BOX</h3>
								<p>"                                                           "</p>
							</section>
							<section>
								<span class="icon major fa-lock accent5"></span>
								<h3>HOW TO TRADE</h3>
								<p>                                                       </p>
							</section>
						</div>
					</section>

					<div class="row">
						<div class="col-6 col-12-narrower">

							<section class="box special">
								<span class="image featured"><img src={% static "images/pic02.jpg"%}  /></span>
								<h3></h3>
								<p></p>
								
							</section>

						</div>
						<div class="col-6 col-12-narrower">

							<section class="box special">
								<span class="image featured"><img src={% static "images/pic03.jpg"%} /></span>
								<h3></h3>
								<p></p>
								
							</section>

						</div>
					</div>

				</section>

			<!-- CTA -->
				

			<!-- Footer -->
				<footer id="footer">
					<ul class="icons">
						<li><a href="#" class="icon fa-twitter"><span class="label">Twitter</span></a></li>
						<li><a href="#" class="icon fa-facebook"><span class="label">Facebook</span></a></li>
						<li><a href="#" class="icon fa-instagram"><span class="label">Instagram</span></a></li>
						<li><a href="#" class="icon fa-github"><span class="label">Github</span></a></li>
						<li><a href="#" class="icon fa-dribbble"><span class="label">Dribbble</span></a></li>
						<li><a href="#" class="icon fa-google-plus"><span class="label">Google+</span></a></li>
					</ul>
					<ul class="copyright">
						<li> All rights reserved.</li>
					</ul>
				</footer>

		</div>

		<!-- Scripts -->
			<script src="{% static "assets/js/jquery.min.js" %}"></script>
			<script src={% static  "assets/js/jquery.dropotron.min.js" %}></script>
			<script src={% static  "assets/js/jquery.scrollex.min.js"%}></script>
			<script src={% static  "assets/js/browser.min.js" %}></script>
			<script src={% static "assets/js/breakpoints.min.js" %}></script>
			<script src={% static "assets/js/util.js" %}></script>
			<script src={% static  "assets/js/main.js"%}></script>

	</body>
</html>