apps/register/urls.py
from django.urls import path

from . import views
app_name = 'accounts'
urlpatterns = [
    path('', views.index,name='index'),
    path('register/', views.register,name='register'),
    path('success/', views.success),
    path('login/', views.user_login,name='login'),

    path('logout/', views.user_logout, name ='logout')
]

contact/messages/urls.py
from django.conf.urls import url

from . import views

app_name = "pinax_messages"

urlpatterns = [
    url(r"^inbox/$", views.InboxView.as_view(),
        name="inbox"),
    url(r"^create/$", views.MessageCreateView.as_view(),
        name="message_create"),
    url(r"^create/(?P<user_id>\d+)/$", views.MessageCreateView.as_view(),
        name="message_user_create"),
    url(r"^thread/(?P<pk>\d+)/$", views.ThreadView.as_view(),
        name="thread_detail"),
    url(r"^thread/(?P<pk>\d+)/delete/$", views.ThreadDeleteView.as_view(),
        name="thread_delete"),
]

main/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path
from main import settings

from django.conf.urls.static import static
urlpatterns = [
path('Post/', include('products.urls')) ,
path('Notes/', include('notes.urls')) ,
    path('', include('apps.register.urls')),
url(r"^messages/", include("pinax.messages.urls", namespace="pinax_messages")),
url(r'^ratings/', include('star_ratings.urls', namespace='ratings')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

templates/Post/base.html
{% load staticfiles %}
<!--DOCTYPE html -->
<html>
<head>
<title>{% block head_title %}Try Django 1.9{% endblock head_title %}</title>
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">


<link rel='stylesheet' href='{% static "css/main.css" %}' />
<style>
{% block style %}{% endblock style %}
</style>
</head>
<body>
<div id="fb-root"></div>
<script>(function(d, s, id) {
var js, fjs = d.getElementsByTagName(s)[0];
if (d.getElementById(id)) return;
js = d.createElement(s); js.id = id;
js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.5";
fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>




<div class='container'>
{% block content %}{% endblock content %}
</div>



<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
</body>
</html>

templates/Post/messages_display.html
{% if messages %}
    <div class='messages'>

    <ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{% if "html_safe" in message.tags %}{{ message|safe }}{% else %}{{ message }}{% endif %}</li>
    {% endfor %}
    </ul>

    </div>
{% endif %}

templates/Post/post.html
<!DOCTYPE html>
<html>
{% load static %}
{% load crispy_forms_filters %}
<head>
    
    <link rel="stylesheet" href="{%static "assets/css/main.css" %}" />
    <title>POST</title>
    
    </head>
    <style>
      .a {
          font-weight: bold;
           font-family: "Times New Roman", Times, serif;
          font-variant: small-caps;
             font-style: oblique;
    font-size: 20px;
}
    body {
    background-color: #662C91
    }
        .box {
		background: #662C91;
		border-radius: 6px;
		box-shadow: 0 2px 0 0 #662C91;
		margin: 0 0 2em 0;
		padding: 5em;
	}
        .center {
    margin: auto;
    width: 50%;
    border-radius: 25px;
    border: 3px solid #ffffff;
    padding: 10px;
     background-color: #ffffff;
           
            
}
   .animate {
    -webkit-animation: animatezoom 0.6s;
    animation: animatezoom 0.6s
}

@-webkit-keyframes animatezoom {
    from {-webkit-transform: scale(0)} 
    to {-webkit-transform: scale(1)}
}
    
@keyframes animatezoom {
    from {transform: scale(0)} 
    to {transform: scale(1)}
}     
    </style>
    <body>
        
        <!-- Header -->
				<header id="header" class="alt">
					<h1><a href="{% url "accounts:index"  %}">TRADE-EX</a></h1>
					<nav id="nav">
						<ul>
							<li><a href="{% url "accounts:index" %}" >Home</a></li>
							<li>

							</li>
							<li><a href="{% url "accounts:login" %}" class="button">Login</a></li>
						</ul>
					</nav>
				</header>
        
        
        
        
<!-- Submit Ad -->
        <div class="box animate">
        <div class="center">
	<div class="submit-ad main-grid-border">
		<div class="container">
            <h2 class="head"><b>POST AN AD</b></h2>
			<div>
				<form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}<br>
{#                    {% for field in form %}#}
{#                        {% if field.label == 'Media' %}#}
{##}
{#                            <label class="button">#}
{#                    Browse...#}
{#                    <span id="uploaded-file-name" style="font-style: italic"></span>#}
{#                    <input id="file-upload" type="file" name="file"#}
{#                           onchange="$('#uploaded-file-info').text($('#file-upload')[0].value);" >#}
{#                            </label><br>#}
{##}
{##}
{#                        {% else %}#}


                <dvi class="a"   >  {{ form|crispy}}</dvi>
                            <br>

					    {{ field }}
                            <br>

{#                        {% endif %}#}
{#                    {% endfor %}#}

					<br>

					<input type="submit" value="Post">			
            					
                    </form>
            </div>
		</div>	
    </div>
            
        </body>
</html>

templates/Post/post_detail.html
{% load static %}
<head><link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
<script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>

</head>
<style>
    body{
        background-color: #FA824C;
    }
.center {
    margin: auto;
    width: 50%;

    padding: 8px;
}
    .box {

		border-radius: 6px;

		margin: 50px 50px 2em 50px;
		padding: 0em;
	}

</style>




<div class="center">
{% block content %}
<div class='col-sm-6 col-sm-offset-3'>
    {% if instance.media %}
    <img src='{{ instance.media.url }}' class='img-fluid' />
    {% endif %}
</div>

<h1>Title:{{ instance.title }} </h1>

    <div class="box">
    <p><b>SELLER:</b></p>
 {{ instance.user.get_username}}
{% if instance.user.get_username == user.get_username %}
    <a href="{% url 'del' instance.slug %}">Delete</a>
    <a href="{% url 'update' instance.slug %}">Update</a>
{% endif %}

{#<a href="{% url "pinax_messages:message_user_create" user_id=instance.user.id %}" class="btn btn-default">Message {{ instance.user.username }}</a>#}
    <p><b>RATING:</b></p>
{{ avg }}
{% if form %}
<form method="post">{{ form }} <input type="submit" value="Post">		</form>{% endif %}

<div class='row'>
<div class='col-sm-12'>
<p><b>DESCRIPTION:</b></p>
{{ instance.description|linebreaks }}

<hr/>
<br/>
</div>

</div>
</div>
</div>


{% endblock content %}

templates/Post/post_form.html
{% load static %}

{% load crispy_forms_filters %}
<head>
<link href="{% static '/assets/css/main.css' %}" rel="stylesheet">
</head>

<div class='col-sm-6 col-sm-offset-3'>
<h1>Form</h1>

<form method='POST' action='' enctype='multipart/form-data'>{% csrf_token %}


{{ form|crispy }}



<input type='submit' class='btn btn-default' value='Create Post' ></form></div>

templates/Post/post_list.html
{% load static %}
{% block content %}
{% load thumbnail %}
      <head><link href="{% static '/assets/css/main.css' %}" rel="stylesheet"></head>
<style>
 * {
            margin: 0;
            padding: 0;
        }
        .imgbox {
            display: grid;
            height: 100%;
        }
        .center-fit {
            max-width: 100%;
            max-height: 70vh;
            margin: auto;
        }
body{
    background-color: #0471A6;
}
.centr1{
    position: relative;
    margin: auto;
    width: 50%;

    padding: 20px;

}
.footer {
    position: fixed;
    bottom: 0;
    width: 100%;
    margin-left: 40%;
}
.box {
		background: #ffffff;
		border-radius: 6px;
		box-shadow: 0 2px 0 0 #fff;
		margin: 50px 50px 2em 50px;
		padding: 3em;
	}

.col {
    float: left;
    width: 33.33%;
    padding: 5px;
}
.animate {
    -webkit-animation: animatezoom 0.6s;
    animation: animatezoom 0.6s
}

@-webkit-keyframes animatezoom {
    from {-webkit-transform: scale(0)}
    to {-webkit-transform: scale(1)}
}

@keyframes animatezoom {
    from {transform: scale(0)}
    to {transform: scale(1)}
}
</style>
<section>
<div class='col-sm-6 col-sm-offset-3'>
<div class="centr1">
<form method='GET' action=''>
    <div class="row gtr-uniform gtr-50">
        <div class="col-9 col-12-mobilep">
<input type='text' name='q' placeholder='Search posts' value='{{ request.GET.q }}'/>
    </div>

<div class="col-3 col-12-mobilep">
<input type='submit' value='Search' class="fit" />
</div></div>
</form></div>

{% if object_list is null %}
    <div class="box animate">
    <div class="center">
<div class="row">
    <div class="col-sm-12">   <div class="caption"><p>NO items</p></div></div></div></div></div>
{% else %}

{% for obj in object_list %}
<div class="col">

    <div class="box animate">
    <div class="center">
<div class="row">
  <div class="col-sm-12">
    <div class="thumbnail">

        {% if obj.media %}

             {% thumbnail obj.media "300x450"  as im %}
            <img class ="center-fit" src="{{ im.url }}"  >
            {% endthumbnail %}

        {% endif %}
      <div class="caption">

        <h3><a href='{{ obj.get_absolute_url }}'>{{ obj.title }}</a> <small>{{ obj.publish }}</small></h3>
        {% if obj.user.get_full_name %}<p>Author: {{ obj.user.get_full_name }}</p>{% endif %}
        <p>{{ obj.content|linebreaks|truncatechars:120 }}</p>
        <p><a href="{{ obj.get_absolute_url }}" class="button special icon fa-search" role="button">View Post</a></p>
      </div>
    </div>
  </div>
        </div>
</div></div></div>
{% endfor %}

</div>
{% endif %}
{% endblock content %}

<div class="footer">
<div class="pagination">
    <span class="step-links">
        {% if object_list.has_previous %}
            <a href="?{{ page_request_var }}={{ object_list.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.
        </span>

        {% if object_list.has_next %}
            <a href="?{{ page_request_var }}={{ object_list.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">next</a>
        {% endif %}
    <a href="{% url 'index' %}">Prodcuts  </a>
    <a style="margin-left: 5px "  class="red" href="{% url 'accounts:index' %}">Home</a>
    </span>
</div></div>


</section>